# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9722f820-5db0-4630-abe8-9248c457e9ac";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f4b86a49-7907-414c-94ae-db8ec73cb210".device = "/dev/disk/by-uuid/f4b86a49-7907-414c-94ae-db8ec73cb210";
  boot.initrd.luks.devices."luks-59a862b8-c3c7-4265-8e54-d3575557ce71".device = "/dev/disk/by-uuid/59a862b8-c3c7-4265-8e54-d3575557ce71";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/78E9-972C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/20a7b3ab-6783-4f3f-b4cb-aca8c227924b"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
